# Generated by Django 2.0.6 on 2021-09-17 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='animales',
            fields=[
                ('pk_colores', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('diagnostico', models.CharField(max_length=500)),
                ('medicamentos', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('imagen', models.URLField(default='https://i.ibb.co/0JZN3GS/6034d7d1f3e0f54a99b2b2bd-Mujercitas-louisa-may-alcott-editorial-alma.jpg', max_length=8000)),
            ],
        ),
        migrations.CreateModel(
            name='colores',
            fields=[
                ('pk_colores', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='especies',
            fields=[
                ('pk_especies', models.AutoField(primary_key=True, serialize=False)),
                ('especie', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='razas',
            fields=[
                ('pk_razas', models.AutoField(primary_key=True, serialize=False)),
                ('raza', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='animales',
            name='fk_especies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Veterinaria.especies'),
        ),
        migrations.AddField(
            model_name='animales',
            name='fk_razas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Veterinaria.razas'),
        ),
    ]
